//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProMaster.Infrastructure.UserProfile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lease
    {
        public int LeaseId { get; set; }
        public string LeaseTitle { get; set; }
        public string LeaseDesc { get; set; }
        public int PropertyId { get; set; }
        public System.DateTime LeaseStartDate { get; set; }
        public System.DateTime LeaseEndDate { get; set; }
        public int LeaseTermId { get; set; }
        public string RentFrequency { get; set; }
        public decimal RentAmount { get; set; }
        public string RentDueOn { get; set; }
        public decimal DamageDepositAmount { get; set; }
        public Nullable<decimal> PetDepositAmount { get; set; }
        public System.DateTime LeaseSignDate { get; set; }
        public string LeaseAgreementDocUrl { get; set; }
        public bool IsActive { get; set; }
        public bool Addendum { get; set; }
        public string Notes { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual LeaseTerm LeaseTerm { get; set; }
        public virtual Property Property { get; set; }
    }
}
