//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProMaster.Infrastructure.UserProfile
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProMasterUserProfileDataEntities : DbContext
    {
        public ProMasterUserProfileDataEntities()
            : base("name=ProMasterUserProfileDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<PropertyManager> PropertyManagers { get; set; }
        public DbSet<PropertyOwner> PropertyOwners { get; set; }
        public DbSet<Tenant> Tenants { get; set; }
        public DbSet<Lease> Leases { get; set; }
        public DbSet<LeaseTerm> LeaseTerms { get; set; }
        public DbSet<Property> Properties { get; set; }
        public DbSet<PropertyType> PropertyTypes { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
    }
}
